#%RAML 1.0 DataType
properties:
  OrganizationName:
    type: string
    required: true
    example: "Johnston-Larson"
  Address:
    type: string
    required: true
    example: "Sharron"
  City:
    type: string
    required: true
    example: "Wangcao"
  State:
    type: string
    required: true
    example: "Shansui"
  Zip:
    type: string
    required: true
    example: "123456"
  PhoneNumber:
    type: number
    required: true
    example: 3835027044
  Revenue:
    type: number
    required: true
    example: 100000

